@startuml Manage Shop (GET)

header Sameple Massage Shop Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Shop (POST)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:shops" as routerShops
participant "<<controllers>>\n:shops" as controllersShops
participant "<<model>>\n:Shop" as modelShop
database "<<MongoDB>>\n:shops" as ShopsDatabase

client->server ++:req.get('/shops/:shopID')
server->routerShops ++:app.use('/shops',shops)
routerShops -> controllersShops ++:getShop()
controllersShops->modelShop ++:get(req.body)
modelShop ->ShopsDatabase ++: shopSchema
ShopsDatabase --> modelShop --: shop
controllersShops <-- modelShop --:shop
controllersShops->client --:response

@enduml
